[build]
builder = "DOCKERFILE"
dockerfilePath = "web/Dockerfile"

[deploy]
startCommand = "apache2-foreground"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
APP_ENV = "production"