[build]
builder = "DOCKERFILE"
dockerfilePath = "rasa/Dockerfile"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
RASA_ENVIRONMENT = "production"
PORT = "8080"